### ISSUE TITLE
maven support

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [blablacar/dgr#173]
the readme gives example of maven use
https://github.com/blablacar/dgr/blob/33b72e7bb3e8f1a58db71303b262d8b511aec41b/README.md#L78

but the code actually disables it for general use
https://github.com/blablacar/dgr/blob/33b72e7bb3e8f1a58db71303b262d8b511aec41b/bin-dgr/aci-push.go#L43
https://github.com/blablacar/dgr/blob/66a4153fd6bda31ad8ac62323adf16b019da1b49/bin-dgr/pod-push.go#L27

can you please enable?

**Comment by n0rad** [comment]
We are using a combination of nginx lua script+nexus as aci repository @BlaBlaCar because the push spec did not exist when starting dgr.

When I implemented the push spec, I thought that the support of nexus should be removed.
If you still want to use nexus instead of a push spec compatible server, I can export nexus configuration (especially the groupId to dgr config file) and keep nexus support.

**Comment by Andrei-Pozolotin** [comment]
1) yes, we would like to keep maven/nexus option
* it would be wrong to discard your efforts
* hopefully will motivate `rkt` be more flexible about repo types

2) would it be possible to use nexus directly, w/o any scripts?
not sure why script layer was needed in the first place

3) can/should `dgr` deprecate `push:` config section in favor of
`/etc/rkt/auth.d/conf.json::"type": "maven"`?
https://coreos.com/rkt/docs/latest/configuration.html

4) to reduce newcomer confusion it would probably help 
to create additional acserver (non-maven) example
https://github.com/blablacar/dgr#configuration-file

**Comment by n0rad** [comment]
Using nexus to store aci is a hack, nexus can store files but do not provide discovery mechanism, this is why it needs a script in front of it. We did it because no push server exists when starting dgr.

Keeping nexus support will require more work than removing it actually. Since it's kind of hard coded for blablacar and providing it wider will require extra work.

We will focus our work on using the push spec and a clean minimal acserver.

I will update the readme to remove maven info.

**Comment by Andrei-Pozolotin** [comment]
`clean minimal acserver` sounds good
